name = 'echo-server'
command = ["node", "webserver", "--port", "8000"]

[image]
image = 'ealen/echo-server:latest'

[[ports]]
port = 8000
type = 'http'
publish = true

[[ports.ingresses]]
fqdn = [ "echo.nhost.nestormanrique.com" ]

[resources]
replicas = 1

[resources.compute]
cpu = 62
memory = 128

[healthCheck]
port = 8000
initialDelaySeconds = 11
probePeriodSeconds = 21