name = "httpbin"

[image]
image = "kong/httpbin"

[[ports]]
port = 80
publish = true
type = "http"

  [ports.ingress]
  fqdn = [ "httpbin.nhost.nestormanrique.com" ]

[resources]
replicas = 1

  [resources.compute]
  cpu = 62
  memory = 128